### PR TITLE
WIP: Correcting sample code for with Maybe

### PR DESCRIPTION
**Pull request by imcotton**
Should have been `map` instead of `chain` over here.

### CODE REVIEW

**Comment by gigobyte** [comment]
The `Maybe` example code assumes that there are no nullable types and that everything is Maybe. In this case, the type of `port` would be `Maybe<number>` and if you only map it you would get `<Maybe<Maybe<number>>` which is why chain is used.

**Comment by imcotton** [comment]
But how would you create this `getConfig()` in practice? I would assume the following

```typescript
function getConfig () {
    return Maybe.of({ port: 80 });
}
```

Then, shouldn't you plunk it by `map` as below?

```typescript
getConfig().map(config => config.port)
```

**Comment by imcotton** [comment]
I think you are right about `Maybe<number | null>` and its assumption in the sample code.

What confuses me is in practice (i.e. existing codebase), there should be one `Config` interface where describes its shape in arbitrary type `{ port?: string | number }` beforehand, with introducing **purify-ts** in middle layer one couldn't afford to alter every type to `{ port: Maybe<string | number> }`, so that 99% chances you would end up by using `map` instead of `chain`?

**Comment by gigobyte** [comment]
The problem with map and having a nullable property is that if the port is undefined you will end up with `Just(undefined)` which means that you lose all benefits of using Maybe. For example:

```typescript
const configPort: Maybe<number | undefined> = getConfig().map(x => x.port)
const port = Just(configPort).orDefault(8080)
```
the type of the `port` variable will be `number | undefined` and it's value will be undefined since `orDefault` only checks for Nothing. It's very misleading.

**Comment by imcotton** [comment]
I see, so either

    getConfig().map(x => Maybe.fromNullable(x.port))

or

    getConfig().mapNullable(x => x.port)

as you've mentioned on above.

**Comment by imcotton** [comment]
Cool, thanks for taken the time on this, I now have better understanding, looking forward on its further development 😄

**Pull request closed without merging**
